site_name: Zeus
nav:
    - Home: 'index.md'
    - Developer Manual: 'development.md'
    - Coding Style: 'style.md'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
    - toc:
        permalink: "#"
    - tables
    - fenced_code
    - pymdownx.arithmatex
theme: slate
