target-version = "py312"
line-length = 90
indent-width = 4
src = ["scripts"]

[lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "N",
    "A",
    "C4",
    "T10",
    "ICN",
    "PIE",
    "SLF",
    "PTH",
    "ERA",
    "NPY",
    "RUF100",
]

ignore = []
fixable = ["I"]
unfixable = []

[lint.pydocstyle]
convention = "pep257"

[format]
line-ending = "lf"
