name: Build Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.preset }}-${{ matrix.build }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {cxx: "clang++-18", cc: "clang-18", preset: "clang"}
          - {cxx: "g++-14", cc: "gcc-14", preset: "gcc"}
        build: ["Debug", "Release"]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/deps
          key: deps-${{ runner.os }}-${{ hashfiles('dependencies.txt') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          chmod +x .github/workflows/scripts/install_deps.sh
          ./.github/workflows/scripts/install_deps.sh

      - name: Build
        shell: bash
        env:
          BUILD_TYPE: ${{ matrix.build }}
          CONFIG_TYPE: ${{ matrix.config.preset }}
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake --preset=$CONFIG_TYPE --config $BUILD_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=~/deps
          cd ./build
          make

      - name: Run tests
        shell: bash
        working-directory: ./build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          make test
