name: Check clang-format

on:
  workflow_call:

jobs:
  formatting-check:
    name: check ${{ matrix.path['check'] }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "include"
            exclude: "(zeus\\.hpp)"
          - check: "test"
            exclude: ""
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: "20"
        check-path: ${{ matrix.path['check'] }}
