name: MSVC

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "MSVC Debug",
            os: windows-latest,
            build_type: "Debug",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "MSVC Release",
            os: windows-latest,
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: zeus_deps
        with:
          path: C:/deps
          key: ${{ env.cache-name }}-build-${{ matrix.config.build_type }}

      - name: Install dependencies
        shell: powershell
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          $c="C:/deps"
          if(-not (Test-Path $c))
          {
            git clone https://github.com/fmtlib/fmt.git --branch 9.1.0 --depth 1
            cmake -G "Visual Studio 17 2022" -S fmt -B fmt/build -DFMT_INSTALL=ON -DCMAKE_INSTALL_PREFIX=C:/deps/fmt
            cd ./fmt/build
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL
            cd ../..
            git clone https://github.com/catchorg/Catch2.git --branch v3.3.2 --depth 1
            cmake -G "Visual Studio 17 2022" -S Catch2 -B Catch2/build -DINSTALL_DOCS=OFF -DINSTALL_EXTRAS=OFF -DCMAKE_INSTALL_PREFIX=C:/deps/Catch2
            cd ./Catch2/build
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL
          }

      - name: Build
        shell: powershell
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          cmake --preset=msvc -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=C:/deps
          cd ./build
          cmake --build . --config $env:BUILD_TYPE

      - name: Run tests
        shell: powershell
        working-directory: ./build
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          cmake --build . --target RUN_TESTS --config $env:BUILD_TYPE
